name: 'LockBot'

on:
  schedule:
    - cron: '0 1 * * *'

permissions:
  issues: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v2
        with:
          issue-lock-inactive-days: '90'
          issue-lock-comment: 'This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related issues.'